//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public books()
        {
            this.bookauthors = new HashSet<bookauthors>();
            this.bookauthors1 = new HashSet<bookauthors>();
            this.genres = new HashSet<genres>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> FSKID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ratingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookauthors> bookauthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookauthors> bookauthors1 { get; set; }
        public virtual fsk fsk { get; set; }
        public virtual publisher publisher { get; set; }
        public virtual category category { get; set; }
        public virtual users users { get; set; }
        public virtual ratings ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genres> genres { get; set; }
    }
}
