//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookhubEntities : DbContext
    {
        public bookhubEntities()
            : base("name=bookhubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<bookauthors> bookauthors { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<credentials> credentials { get; set; }
        public virtual DbSet<fsk> fsk { get; set; }
        public virtual DbSet<genres> genres { get; set; }
        public virtual DbSet<publisher> publisher { get; set; }
        public virtual DbSet<ratings> ratings { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
